GRANT all privileges ON DAW204_Alima.* TO "DAW204"@"%" IDENTIFIED BY "paso";
DROP SCHEMA IF EXISTS DAW204_Alima;
CREATE DATABASE DAW204_Alima;
USE DAW204_Alima;
CREATE TABLE IF NOT EXISTS Usuario (
	codigo VARCHAR(15) PRIMARY KEY NOT NULL,
	password VARCHAR(64) NOT NULL,
	email VARCHAR(50) UNIQUE NOT NULL,
	nombre VARCHAR(40) NOT NULL,
	sexo VARCHAR(1),
	fechaNac VARCHAR(10) NOT NULL,
	estatura INT(3) NOT NULL,
	peso INT(3) NOT NULL
)ENGINE=INNODB;