GRANT all privileges ON DAW204_Alima.* TO "DAW204"@"%" IDENTIFIED BY "paso";
DROP SCHEMA IF EXISTS DAW204_Alima;
CREATE DATABASE DAW204_Alima;
USE DAW204_Alima;
CREATE TABLE IF NOT EXISTS Usuario (
	codigo VARCHAR(15) PRIMARY KEY NOT NULL,
	password VARCHAR(64) NOT NULL,
	email VARCHAR(50) UNIQUE NOT NULL,
	nombre VARCHAR(40) NOT NULL,
	sexo VARCHAR(1),
	fechaNac VARCHAR(10) NOT NULL,
	estatura INT(3) NOT NULL,
	peso INT(3) NOT NULL
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS Track(
	codigo int AUTO_INCREMENT PRIMARY KEY,
	codigoU VARCHAR(15),
	visibilidad BOOLEAN,
	nombre VARCHAR(100),
	fechaImportacion VARCHAR(11),
	fechaInicio VARCHAR(11),
	FOREIGN KEY (codigoU) REFERENCES Usuario(codigo) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS Trackpoint(
	codigo int AUTO_INCREMENT PRIMARY KEY,
	codigoT INT(255),
	latitud FLOAT,
	longitud FLOAT,
	tiempo VARCHAR(20),
	heartRate INT(3),
	elevacion FLOAT,
	FOREIGN KEY (codigoT) REFERENCES Track(codigo) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB;